/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadgrupo6.vistas;

import java.util.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadgrupo6.accesoADatos.AlumnoData;
import universidadgrupo6.entidades.Alumno;

/**
 *
 * @author elise
 */
public class FormularioAlumnoView extends javax.swing.JInternalFrame {

     AlumnoData alumnoData= new AlumnoData();
     Alumno alumnoActual= null;
        
    public FormularioAlumnoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLAlumno = new javax.swing.JLabel();
        jLDocumento = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jBNuevo = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jTFDocumento = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jRBEstado = new javax.swing.JRadioButton();
        jDFechaNac = new com.toedter.calendar.JDateChooser();

        jTextField1.setText("jTextField1");

        jRadioButton2.setText("jRadioButton2");

        setIconifiable(true);
        setResizable(true);

        jLAlumno.setText("Alumno");

        jLDocumento.setText("Documento");

        jLApellido.setText("Apellido");

        jLNombre.setText("Nombre");

        jLEstado.setText("Estado");

        jLFechaNac.setText("Fecha de Nacimiento");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTFDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDocumentoActionPerformed(evt);
            }
        });

        jRBEstado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLDocumento)
                            .addComponent(jLApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFApellido)
                            .addComponent(jTFDocumento)
                            .addComponent(jTFNombre))
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jBEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jBGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jBSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLFechaNac)
                                .addGap(18, 18, 18)
                                .addComponent(jDFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEstado)
                                .addGap(44, 44, 44)
                                .addComponent(jRBEstado)))
                        .addGap(29, 29, 29)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLAlumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLAlumno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDocumento)
                    .addComponent(jBBuscar)
                    .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEstado)
                    .addComponent(jRBEstado))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFechaNac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBEliminar)
                    .addComponent(jBGuardar)
                    .addComponent(jBSalir))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDocumentoActionPerformed
   
    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
       
        try{
           Integer dni=Integer.parseInt(jTFDocumento.getText());
 
           alumnoActual= alumnoData.buscarAlumnoPorDni(dni);
                   
            if(alumnoActual!= null){
                jTFApellido.setText(alumnoActual.getApellido());
                jTFNombre.setText(alumnoActual.getNombre());
                jRBEstado.setSelected(alumnoActual.isEstado());
                LocalDate lc=alumnoActual.getFechaNacimiento();
                java.util.Date date =java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
              jDFechaNac.setDate(date);
            }
            
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this,"ingrese un dni valido");
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this,"Exception"+ex.getMessage());
           ex.printStackTrace();
       }
       
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
       limpiarCampos();
       alumnoActual=null;
       
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try{
            Integer dni=Integer.parseInt(jTFDocumento.getText());
            String nombre=jTFNombre.getText();
            String apellido=jTFApellido.getText();
            if(nombre.isEmpty()|| apellido.isEmpty()){
               JOptionPane.showMessageDialog(this,"No puede haber campos vacios");
               return;
            }
            java.util.Date esFecha =jDFechaNac.getDate();
            LocalDate fechaNac=esFecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            boolean estado=jRBEstado.isSelected();
            if(alumnoActual==null){
                alumnoActual=new Alumno(dni,nombre,apellido,fechaNac,estado);
                alumnoData.guardarAlumno(alumnoActual);
            }else{
                alumnoActual.setDni(dni);
                alumnoActual.setNombre(nombre);
                alumnoActual.setApellido(apellido);
                alumnoActual.setFechaNacimiento(fechaNac);
               alumnoData.modificarAlumno(alumnoActual);
                
            }
            
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this,"ingrese un dni valido");
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this,"Exception"+ex.getMessage());
           ex.printStackTrace();
       }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        if(alumnoActual != null){
            alumnoData.eliminarAlumno(alumnoActual.getIdAlumno());
            alumnoActual=null;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this,"No existe el alumno a eliminar");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed
   private void limpiarCampos(){
       jTFDocumento.setText("");
       jTFNombre.setText("");
       jTFApellido.setText("");
       jRBEstado.setSelected(true);
       jDFechaNac.setDate(new Date());
       
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDFechaNac;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDocumento;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLNombre;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JRadioButton jRadioButton2;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDocumento;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
